### ISSUE TITLE
Setup slackin

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/website#26]
1. https://github.com/rauchg/slackin/#usage
2. Most people seem to use Heroku, but now should work too
3. Plug in the info needed to set it up
* For the API token, [they suggest](https://github.com/rauchg/slackin#tips) setting up a dedicated user for inviting and using that users API token. There is also a link in the above URL for recaptcha

**Comment by Glavin001** [comment]
Slackin looks good! @szeck87 would you like to tackle setting it up?

**Comment by szeck87** [comment]
I can try again, I don't think I have the rights though to get the proper token and setup the dummy user.

**Comment by Glavin001** [comment]
Hmm OK let me know how it goes. If you get blocked I can take over or try to get you access you need.

**Comment by Glavin001** [comment]
Already done!

See footer:
![image](https://user-images.githubusercontent.com/1885333/36060249-0b0369f6-0e1c-11e8-81df-6ad92db18bf5.png)
