### ISSUE TITLE
Edit button on option detail pages is broken

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/website#77]
* Individual option detail page
* Individual language page
* Individual beautifier page

![screen shot 2018-04-25 at 11 09 13 am](https://user-images.githubusercontent.com/8315038/39258267-31dcf8de-4879-11e8-9706-16d52f2d6627.png)

**Comment by Glavin001** [comment]
# Reproduce
Go to https://unibeautify.com/docs/option-align-assignments.html
Edit button goes to https://github.com/unibeautify/website/edit/master/docs/option-align-assignments.md

# Analysis

Looking at the applicable code: https://github.com/Unibeautify/website/blob/master/scripts/generate-docs/OptionsDoc.ts#L57-L59
The edit button should go to https://github.com/unibeautify/unibeautify/edit/master/src/options.ts

This indicates to me Docusaurus is not respecting the changes from my PR. Maybe the version does not include my changes?

From https://github.com/Unibeautify/website/commit/30b547674358099b5add77f11854a0f48d358e61

![image](https://user-images.githubusercontent.com/1885333/39263549-e790c57e-4898-11e8-9569-43a4f9a24678.png)

Looking at versions from https://www.npmjs.com/package/docusaurus

> 1.0.9 a month ago

My PR was well over a month ago: https://github.com/facebook/Docusaurus/pull/443

Do we need https://github.com/facebook/Docusaurus/pull/604 to be published?

🔥 I'm confused 🔥 

Will debug more later tonight.

**Comment by Glavin001** [comment]
Will be fixed as part of https://github.com/Unibeautify/website/pull/76

**Comment by Glavin001** [comment]
#76 is taking too long. Fixed as part of https://github.com/Unibeautify/website/pull/80
